In [ ]:
!source ~/scratch/venvs/e3_diff/bin/activate

In [3]:
import os.path as osp
import os

# from torch_geometric.data import Data
#from torch_geometric.loader import DataLoader
import torch
#from torch_geometric.data import Dataset, download_url
import Bio.PDB
from Bio import SeqIO
import os
import numpy as np
import torch
import argparse
import warnings
import data.utils as utils
warnings.filterwarnings("ignore") # toggle

import data.embeddings
import math


ModuleNotFoundError: No module named 'data'

In [ ]:
dim = 256

def forward(time: torch.Tensor) -> torch.Tensor:
    #device = time.device
    half_dim = dim // 2
    embeddings = math.log(10000) / (half_dim - 1)
    # half_dim shape
    embeddings = torch.exp(torch.arange(half_dim) * -embeddings)
    # outer product (batch, 1) x (1, half_dim) -> (batch x half_dim)
    embeddings = time[:, None] * embeddings[None, :]
    # sin and cosine embeddings
    embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)

    return embeddings

In [ ]:
edge_index = torch.ones(100, 100).fill_diagonal_(0)

edge_features = []
for i in range(100):
    for j in range(100):
        elem = torch.tensor([i-j])
        edge_features.append(forward(elem).T)

result = torch.cat(edge_features, dim=1)
result = result.reshape(100, 100, 256)

In [ ]:
x_features = forward(torch.tensor([100])).T + \
torch.matmul(torch.tensor(utils.get_R(torch.tensor([256]))).double(),  forward(torch.tensor([0])).T.double())
           

In [ ]:
from torch.linalg import qr

def get_R(n):
    H = torch.randn(n, n)
    Q, R = qr(H)
    return torch.mm(Q.t(), Q)

get_R(256).shape

In [ ]:
dataloader.StructureData(Dataset)

In [ ]:
from sequence_models.pretrained import load_model_and_alphabet

model, collater = load_model_and_alphabet('carp_600k')

x = collater(['MGTRRLJJJLPHT'])[0]
rep = model(x) 

In [ ]:
rep['representations'][16].shape

In [ ]:


model, collater = load_model_and_alphabet('carp_38M')

x = collater(['MGTRRLLHHHPHT'])[0]
rep = model(x) 

In [ ]:
x = torch.ones(1, 3)
y = torch.ones(1, 256)
z = torch.ones(1, 128)

In [ ]:
torch.cat(((x) , (y), (z)), dim=1).shape

In [ ]:
3+256+128

In [ ]:
torch.load('/users/rvinod/data/rvinod/cath/processed/data_7314.pt')

In [ ]:
torch.load('/users/rvinod/data/rvinod/tmp/processed/data_0.pt')

In [ ]:
!pip install prody

In [ ]:
from prody import *

In [ ]:
cath = CATHDB('cath.xml')

result = cath.search('2kdlA00')

print(result.name)

result = cath.search('2kdlA')

print(result.name)

result = cath.search('2kdlA')

print(result.getDomains())

In [ ]:
result = cath.search('3kg2')

In [ ]:
result.name

In [ ]:
result = cath.search('4fx5')

In [ ]:
result.name

In [ ]:
result = cath.search ('4fx5')

In [ ]:
result.name

In [ ]:
!wget http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/1cukA01

In [ ]:
!ls

In [ ]:
! vim 1cukA01

In [ ]:
import requests
from bs4 import BeautifulSoup
url = "http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/1cukA01"

html = requests.get(url).text
print(html)

In [ ]:
import ast

In [ ]:
!pip3 install --user bs4

In [ ]:
import requests
import json

url = "http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/2vszB02"
html = requests.get(url).text
res = json.loads(html)
res['data']['s35_id']


In [ ]:
def get_cath_code(url):
    html = requests.get(url).text
    res = json.loads(html)
    code_class = res['data']['s35_id'].split('.')[0]
    return code_class #cath_codes[code_class]

In [ ]:
get_cath_code(url)

In [ ]:
import utils
y_url = 'http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/2vszB02' 
y = utils.get_cath_code(y_url)

In [ ]:
import torch

In [ ]:
utils.get_cath_code('http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/2v7qI00')

In [ ]:
!source ~/scratch/venvs/e3_diff/bin/activate
!module load python/3.7.4

In [ ]:
import torch
import torch_sparse
torch.load('/users/rvinod/data/rvinod/cath/processed/data_1671.pt')

In [ ]:
!pip install --user torch_sparse

In [ ]:
utils.get_cath_code('http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/1xdpA04')

In [ ]:
import requests
import json

url = 'http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/1xdpA04'

def get_cath_code(url):
    html = requests.get(url).text
    res = json.loads(html)
    with open(res, "r") as read_file:
        data = json.load(read_file)
        code_class = data['data']['s35_id'].split('.')[0]
    return torch.tensor(int(code_class)) #cath_codes[code_class]


In [ ]:
get_cath_code('http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/1xdpA04')

In [ ]:
!pip3 install --user urllib

In [ ]:
import urllib



In [ ]:
import urllib.request as urllib

In [ ]:
infile = urllib.urlopen(url)

In [ ]:
infile

In [ ]:
dict(infile.read())

In [ ]:
infile = urllib.urlretrieve(url, filename='webpage.html')


In [ ]:
infile 


In [ ]:
infile

In [ ]:
# URL Error
  
import urllib.request
import urllib.parse

def url_cath(url):
    # trying to read the URL but with no internet connectivity
    try:
        x = urllib.request.urlopen(url)
        x = x.read()
    
    # Catching the exception generated     
    except Exception as e :
        print(str(e))
        return torch.tensor(0)
    
    return torch.tensor(int(json.loads(x.decode('utf-8'))['data']['s35_id'].split('.')[0]))


In [ ]:
url_cath('http://www.cathdb.info/version/v4_3_0/api/rest/domain_summary/2x5dA01')

In [ ]:
nodes1 = torch.arange(129)
nodes2 = torch.arange(129)

In [ ]:
rows, cols = [], []
edges = []
for i in range(129):
    for j in range(i, 129):
        if i!=j:
         edges.append([i, j])

In [ ]:
torch.tensor(edges).T.shape

In [ ]:
129*128/2

In [ ]:
import data.embeddings as embeddings

In [ ]:
edge_attr = []
for e in edges:
    elem = torch.tensor([e[1] - e[0]])
    print(elem)
    edge_attr.append(embeddings.SinusoidalPositionEmbeddings(256).forward(elem).T)


In [ ]:
edge_attr = torch.cat(edge_attr)

In [ ]:
edge_attr.reshape(-1, 256).size()

In [ ]:
import torch
from torch.nn import Linear
from torch_geometric.nn import GCNConv


class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        torch.manual_seed(1234)
        self.conv1 = GCNConv(dataset.num_features, 4)
        self.conv2 = GCNConv(4, 4)
        self.conv3 = GCNConv(4, 2)
        self.classifier = Linear(2, dataset.num_classes)

    def forward(self, x, edge_index):
        h = self.conv1(x, edge_index)
        h = h.tanh()
        h = self.conv2(h, edge_index)
        h = h.tanh()
        h = self.conv3(h, edge_index)
        h = h.tanh()  # Final GNN embedding space.
        
        # Apply a final (linear) classifier.
        out = self.classifier(h)

        return out, h

model = GCN()
print(model)

In [ ]:
y = torch.tensor(3)

In [ ]:
y

In [ ]:
y_ = torch.full((5, 1), (y))

In [ ]:
y_.shape

In [ ]:
y_.shape[0]

In [4]:
def get_edges(n_nodes):
    rows, cols = [], []
    for i in range(n_nodes):
        for j in range(n_nodes):
            if i != j:
                rows.append(i)
                cols.append(j)

    edges = [rows, cols]
    return edges


def get_edges_batch(n_nodes, batch_size):
    print('getting edges...')
    edges = get_edges(n_nodes)
    edge_attr = torch.ones(len(edges[0]) * batch_size, 256)
    edges = [torch.LongTensor(edges[0]), torch.LongTensor(edges[1])]
    if batch_size == 1:
        return edges, edge_attr
    elif batch_size > 1:
        rows, cols = [], []
        for i in range(batch_size):
            rows.append(edges[0] + n_nodes * i)
            cols.append(edges[1] + n_nodes * i)
        edges = [torch.cat(rows), torch.cat(cols)]
    
    print('batched edges', edge_attr.shape)
    return edges, edge_attr

In [5]:
edges, edge_attr = get_edges_batch(111, 1)

getting edges...


In [6]:
edges

[tensor([  0,   0,   0,  ..., 110, 110, 110]),
 tensor([  1,   2,   3,  ..., 107, 108, 109])]

In [20]:
from torch import nn


In [23]:
x = torch.rand(471, 256)

In [22]:
mlp = nn.Sequential(
            nn.Linear(256, 64),
            nn.SiLU(),
            nn.Linear(64, 1))


In [25]:

mlp(x).shape

torch.Size([471, 1])

In [31]:
a = torch.tensor([3, 2])  

In [32]:
b = torch.tensor([1, 4])

In [33]:
a- b

tensor([ 2, -2])

In [38]:
torch.full((5, ), -1)

tensor([-1, -1, -1, -1, -1])

In [51]:
from torch.nn import Linear
from torch_geometric.nn import global_mean_pool


ModuleNotFoundError: No module named 'torch_sparse'

In [52]:
class MLP(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.lin = Linear(hidden_channels, 6)

    def forward(self, batch):

        # 1. Obtain node embeddings 

        # 2. Readout layer
        h = global_mean_pool(h, batch)  # [batch_size, hidden_channels]

        # 3. Apply a final classifier
        # h = F.dropout(h, p=0.5, training=self.training)
        h = self.lin(h)
        
        return h

In [53]:
mlp = MLP(256)

In [54]:
mlp(torch.rand(471, 256))

NameError: name 'global_mean_pool' is not defined

In [55]:
torch.rand(471, 256)

tensor([[0.3759, 0.1098, 0.8241,  ..., 0.7323, 0.9858, 0.3189],
        [0.2970, 0.8832, 0.3951,  ..., 0.7541, 0.7782, 0.9583],
        [0.1297, 0.4976, 0.2222,  ..., 0.2080, 0.3057, 0.9345],
        ...,
        [0.5604, 0.9808, 0.2909,  ..., 0.7685, 0.0218, 0.6660],
        [0.5542, 0.3980, 0.6046,  ..., 0.3592, 0.8315, 0.7203],
        [0.8875, 0.7069, 0.0876,  ..., 0.8749, 0.4664, 0.5473]])

In [46]:
torch.cuda.is_available()

False